apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.1
    helm:
      values: |
        defaultSettings:
          defaultReplicaCount: 3
          defaultDataPath: /var/lib/longhorn
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true