apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: homelab

  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 26.0.0
    helm:
      values: |
        service:
          type: LoadBalancer
        ports:
          web:
            port: 8080
            exposedPort: 80
          websecure:
            port: 8443
            exposedPort: 443
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: true
        logs:
          general:
            level: INFO
          access:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
